import { OBELISK_NODES } from "./obelisk";
import type {
  AchievementContext,
  AchievementDefinition,
  BossEvent,
  CharacterDefinition,
  EnemyDefinition,
  ExpeditionProfile,
  ItemDefinition,
  MapDefinition,
  MetaDefinition,
  ModeDefinition,
  PassiveDefinition,
  PathDefinition,
  StatusDefinition,
  StructureDefinition,
  WaveDefinition,
  WeaponDefinition,
} from "../core/types";
export const WEAPON_DEFINITIONS: Record<string, WeaponDefinition> = {
  ember: {
    name: "Brasa de Vidro",
    icon: "◆",
    color: "#ffac75",
    type: "ember",
    damage: 21,
    cooldown: 1.05,
    weight: 12,
    passive: "might",
    evolution: "Aurora Incandescente",
    description: "Lança uma brasa na direção do alvo mais próximo.",
    evolvedDescription: "Brasas maiores explodem e atingem grupos inteiros.",
  },
  orbit: {
    name: "Anéis de Estilhaço",
    icon: "◈",
    color: "#78e5ca",
    type: "orbit",
    damage: 11,
    cooldown: 0.28,
    weight: 10,
    passive: "area",
    evolution: "Órbitas Gêmeas",
    description: "Estilhaços giram ao seu redor.",
    evolvedDescription: "Dois anéis giram em sentidos opostos.",
  },
  spear: {
    name: "Agulha do Vazio",
    icon: "➶",
    color: "#c6b7ff",
    type: "spear",
    damage: 27,
    cooldown: 1.15,
    weight: 11,
    passive: "duration",
    evolution: "Tear Abissal",
    description: "Perfura na última direção de movimento.",
    evolvedDescription: "Oito direções de agulhas atravessam a horda.",
  },
  frost: {
    name: "Sopro de Sal",
    icon: "❄",
    color: "#a8dfff",
    type: "frost",
    damage: 10,
    cooldown: 0.8,
    weight: 10,
    passive: "armor",
    evolution: "Inverno Imóvel",
    description: "Pulsos próximos causam dano e lentidão.",
    evolvedDescription: "Uma grande zona congela inimigos comuns.",
  },
  chain: {
    name: "Fio de Tempestade",
    icon: "ϟ",
    color: "#ffe69d",
    type: "chain",
    damage: 25,
    cooldown: 1.65,
    weight: 8,
    passive: "luck",
    evolution: "Rede Fulgurante",
    description: "Um arco elétrico salta entre alvos.",
    evolvedDescription: "Mais saltos, cada um com uma descarga em área.",
  },
  well: {
    name: "Jardim de Cinzas",
    icon: "✿",
    color: "#d7a2da",
    type: "well",
    damage: 13,
    cooldown: 2.7,
    weight: 9,
    passive: "recovery",
    evolution: "Jardim Devorador",
    description: "Cria campos de dano persistente.",
    evolvedDescription: "Campos atraem inimigos e drenam vida nas baixas.",
  },
  disc: {
    name: "Disco de Nácar",
    icon: "◉",
    color: "#ffcda4",
    type: "disc",
    damage: 19,
    cooldown: 1.55,
    weight: 10,
    passive: "amount",
    evolution: "Coroa Errante",
    description: "Discos retornam e podem acertar duas vezes.",
    evolvedDescription: "Leques de discos explodem ao retornar.",
  },
  meteor: {
    name: "Sino Celeste",
    icon: "✦",
    color: "#fa9ba0",
    type: "meteor",
    damage: 72,
    cooldown: 3.4,
    weight: 7,
    passive: "growth",
    evolution: "Constelação Cadente",
    description: "Marca alvos antes de um impacto celeste.",
    evolvedDescription: "Chuvas de impactos deixam campos ardentes.",
  },
};

export const PASSIVE_DEFINITIONS: Record<string, PassiveDefinition> = {
  might: {
    name: "Selo da Fornalha",
    icon: "♨",
    max: 5,
    weight: 12,
    text: "+10% de dano por nível.",
  },
  speed: {
    name: "Passo de Pluma",
    icon: "»",
    max: 5,
    weight: 10,
    text: "+7% de movimento por nível.",
  },
  vitality: {
    name: "Frasco de Seiva",
    icon: "♥",
    max: 5,
    weight: 11,
    text: "+15% de vida máxima por nível.",
  },
  recovery: {
    name: "Musgo de Âmbar",
    icon: "✚",
    max: 5,
    weight: 9,
    text: "+0,25 de vida por segundo por nível.",
  },
  haste: {
    name: "Ampulheta Fendida",
    icon: "⌛",
    max: 5,
    weight: 9,
    text: "−5% de intervalo entre ataques por nível.",
  },
  area: {
    name: "Compasso Lunar",
    icon: "◎",
    max: 5,
    weight: 10,
    text: "+10% de área por nível.",
  },
  duration: {
    name: "Fita do Crepúsculo",
    icon: "∞",
    max: 5,
    weight: 10,
    text: "+15% de duração por nível.",
  },
  amount: {
    name: "Prisma Partido",
    icon: "⋈",
    max: 2,
    weight: 4,
    text: "+1 projétil / estilhaço por nível.",
  },
  pickup: {
    name: "Bússola de Ecos",
    icon: "⌖",
    max: 5,
    weight: 11,
    text: "+25% de alcance de coleta por nível.",
  },
  growth: {
    name: "Página Viva",
    icon: "▤",
    max: 5,
    weight: 10,
    text: "+5% de experiência por nível.",
  },
  armor: {
    name: "Casca Basáltica",
    icon: "⬡",
    max: 5,
    weight: 10,
    text: "+1 de armadura por nível.",
  },
  luck: {
    name: "Olho de Opala",
    icon: "◌",
    max: 5,
    weight: 8,
    text: "+12% de sorte e +1% de crítico por nível.",
  },
};

export const CHARACTER_DEFINITIONS: Record<string, CharacterDefinition> = {
  nara: {
    name: "Nara",
    title: "A guardiã das brasas",
    weapon: "ember",
    icon: "◆",
    color: "#ffac75",
    bonus: "+10% de movimento. +3% de dano a cada 10 níveis.",
    condition: "Disponível desde o início.",
  },
  orin: {
    name: "Orin",
    title: "O geômetra exilado",
    weapon: "well",
    icon: "◈",
    color: "#78e5ca",
    bonus: "+20% de área. Regenera 0,3 de vida por segundo.",
    condition: "Sobreviva 5 minutos no modo padrão.",
  },
  ivo: {
    name: "Ivo",
    title: "O portador de prismas",
    weapon: "disc",
    icon: "⋈",
    color: "#c6b7ff",
    bonus: "+1 projétil. −15% de vida máxima.",
    condition: "Derrote 1.000 inimigos em uma partida padrão.",
  },
  sena: {
    name: "Sena",
    title: "A leitora do céu",
    weapon: "chain",
    icon: "✦",
    color: "#fa9ba0",
    bonus: "+25% de experiência. +8% de dano.",
    condition: "Evolua uma arma no modo padrão.",
  },
};

export const ENEMY_DEFINITIONS: Record<string, EnemyDefinition> = {
  husk: {
    name: "Errante de Xisto",
    hp: 34,
    speed: 66,
    damage: 15,
    r: 13,
    xp: 2,
    color: "#718d83",
    shape: 5,
    behavior: "chase",
    resist: 0.15,
  },

  dart: {
    name: "Rasante",
    hp: 28,
    speed: 126,
    damage: 12,
    r: 10,
    xp: 3,
    color: "#bd9fa5",
    shape: 3,
    behavior: "chase",
    resist: 0.05,
  },

  tank: {
    name: "Muralha Oca",
    hp: 210,
    speed: 47,
    damage: 30,
    r: 24,
    xp: 10,
    color: "#8898b5",
    shape: 6,
    behavior: "chase",
    resist: 0.9,
  },

  swarm: {
    name: "Cisco Vivo",
    hp: 16,
    speed: 103,
    damage: 8,
    r: 7,
    xp: 1,
    color: "#cdbd8c",
    shape: 4,
    behavior: "chase",
    resist: 0.05,
  },

  ranged: {
    name: "Cantor de Fendas",
    hp: 88,
    speed: 68,
    damage: 20,
    r: 16,
    xp: 6,
    color: "#c38dc0",
    shape: 4,
    behavior: "ranged",
    resist: 0.35,
  },

  elite: {
    name: "Arauto de Basalto",
    hp: 560,
    speed: 72,
    damage: 36,
    r: 28,
    xp: 20,
    color: "#e9ba7e",
    shape: 6,
    behavior: "chase",
    resist: 0.88,
  },

  boss: {
    name: "Custódio",
    hp: 1850,
    speed: 52,
    damage: 42,
    r: 46,
    xp: 60,
    color: "#e8958e",
    shape: 8,
    behavior: "boss",
    resist: 0.97,
  },

  final: {
    name: "A Boca do Firmamento",
    hp: 1000000,
    speed: 148,
    damage: 95,
    r: 64,
    xp: 500,
    color: "#eff5dc",
    shape: 9,
    behavior: "final",
    resist: 1,
  },
  burrower: {
    name: "Escavador da Névoa",
    hp: 72,
    speed: 82,
    damage: 22,
    r: 15,
    xp: 7,
    color: "#907f78",
    shape: 5,
    behavior: "burrow",
    resist: 0.25,
  },
  sentinel: {
    name: "Sentinela de Vidro",
    hp: 145,
    speed: 61,
    damage: 24,
    r: 19,
    xp: 9,
    color: "#9bc7cf",
    shape: 6,
    behavior: "sentinel",
    resist: 0.62,
  },
  herald: {
    name: "Arauto do Véu",
    hp: 120,
    speed: 58,
    damage: 18,
    r: 18,
    xp: 10,
    color: "#d0af77",
    shape: 5,
    behavior: "herald",
    resist: 0.42,
  },
  charger: {
    name: "Rasgador de Laje",
    hp: 115,
    speed: 77,
    damage: 34,
    r: 18,
    xp: 9,
    color: "#c57f78",
    shape: 4,
    behavior: "charger",
    resist: 0.55,
  },
  splitter: {
    name: "Partilhado",
    hp: 96,
    speed: 74,
    damage: 18,
    r: 17,
    xp: 8,
    color: "#a798c8",
    shape: 6,
    behavior: "splitter",
    resist: 0.3,
  },
  shardling: {
    name: "Lasca Viva",
    hp: 22,
    speed: 132,
    damage: 8,
    r: 7,
    xp: 1,
    color: "#baadd6",
    shape: 3,
    behavior: "chase",
    resist: 0,
  },
  weaver: {
    name: "Tecelão de Maré",
    hp: 105,
    speed: 62,
    damage: 19,
    r: 17,
    xp: 10,
    color: "#76aaa4",
    shape: 5,
    behavior: "weaver",
    resist: 0.35,
  },
};

export const WAVE_TABLE: WaveDefinition[] = [
  {
    start: 0,
    end: 60,
    rate: 1.8,
    cap: 100,
    enemies: [
      ["husk", 8],
      ["swarm", 2],
    ],
    elite: 75,
    formation: "scatter",
    name: "O despertar",
  },

  {
    start: 60,
    end: 150,
    rate: 3.5,
    cap: 160,
    enemies: [
      ["husk", 6],
      ["dart", 3],
      ["swarm", 2],
    ],
    elite: 60,
    formation: "flank",
    name: "Passos na névoa",
  },

  {
    start: 150,
    end: 240,
    rate: 5.5,
    cap: 230,
    enemies: [
      ["husk", 4],
      ["dart", 4],
      ["tank", 1],
      ["swarm", 3],
    ],
    elite: 50,
    formation: "ring",
    name: "Pedra e nervo",
  },

  {
    start: 240,
    end: 360,
    rate: 7.5,
    cap: 320,
    enemies: [
      ["husk", 3],
      ["dart", 4],
      ["tank", 2],
      ["swarm", 5],
      ["ranged", 1],
    ],
    elite: 40,
    formation: "swarm",
    name: "O coro das fendas",
  },

  {
    start: 360,
    end: 480,
    rate: 10,
    cap: 420,
    enemies: [
      ["dart", 5],
      ["tank", 2],
      ["swarm", 6],
      ["ranged", 2],
    ],
    elite: 32,
    formation: "flank",
    name: "Maré de estilhaços",
  },

  {
    start: 480,
    end: 600,
    rate: 13,
    cap: 520,
    enemies: [
      ["husk", 2],
      ["dart", 5],
      ["tank", 3],
      ["swarm", 7],
      ["ranged", 3],
    ],
    elite: 25,
    formation: "ring",
    name: "A ruína respira",
  },

  {
    start: 600,
    end: 720,
    rate: 17,
    cap: 650,
    enemies: [
      ["dart", 5],
      ["tank", 4],
      ["swarm", 8],
      ["ranged", 4],
    ],
    elite: 20,
    formation: "swarm",
    name: "O céu se fecha",
  },

  {
    start: 720,
    end: 840,
    rate: 21,
    cap: 760,
    enemies: [
      ["dart", 6],
      ["tank", 5],
      ["swarm", 9],
      ["ranged", 5],
    ],
    elite: 16,
    formation: "flank",
    name: "Antes do silêncio",
  },

  {
    start: 840,
    end: Infinity,
    rate: 27,
    cap: 900,
    enemies: [
      ["husk", 1],
      ["dart", 7],
      ["tank", 6],
      ["swarm", 10],
      ["ranged", 6],
    ],
    elite: 12,
    formation: "ring",
    name: "Além do limiar",
  },
];

export const BOSS_EVENTS: BossEvent[] = [
  {
    at: 240,
    name: "O Sineiro de Pedra",
    pattern: "ring",
  },

  {
    at: 240,
    name: "A Corça de Cobre",
    pattern: "charge",
  },

  {
    at: 360,
    name: "Mãe das Fendas",
    pattern: "summon",
  },

  {
    at: 480,
    name: "O Cartógrafo Cego",
    pattern: "spiral",
  },

  {
    at: 600,
    name: "A Catedral Errante",
    pattern: "pulse",
  },

  {
    at: 690,
    name: "O Peregrino Sem Face",
    pattern: "charge",
  },

  {
    at: 780,
    name: "O Olho Sob a Pedra",
    pattern: "spiral",
  },

  {
    at: 870,
    name: "O Rei das Cinzas",
    pattern: "summon",
  },

  {
    at: 960,
    name: "A Voz do Abismo",
    pattern: "pulse",
  },

  {
    at: 1050,
    name: "O Último Custódio",
    pattern: "ring",
  },
];

const scaledDecisions = (duration: number) =>
  [30, 65, 105, 150, 200, 250, 300, 350, 405, 465, 530, 600, 675, 750, 830, 915, 1000, 1090, 1180, 1270, 1360, 1440, 1520, 1600, 1675, 1745]
    .map((t) => Math.round((t / 1800) * duration))
    .filter((t, i, a) => t > 0 && (i === 0 || t > a[i - 1]));
export const EXPEDITION_LENGTHS: Record<number, ExpeditionProfile> = {
  600: { duration: 600, rewardMultiplier: 0.45, completionBase: 110, decisionSchedule: scaledDecisions(600), bossSchedule: [150, 330, 480], pathTiming: 120, evolutionTiming: 240, waveCompression: 1.35, finalPhase: 480 },
  900: { duration: 900, rewardMultiplier: 0.7, completionBase: 175, decisionSchedule: scaledDecisions(900), bossSchedule: [180, 420, 660, 810], pathTiming: 180, evolutionTiming: 360, waveCompression: 1.15, finalPhase: 720 },
  1800: { duration: 1800, rewardMultiplier: 1, completionBase: 250, decisionSchedule: scaledDecisions(1800), bossSchedule: [240, 480, 720, 1020, 1380, 1740], pathTiming: 360, evolutionTiming: 600, waveCompression: 1, finalPhase: 1500 },
};
export function getExpeditionProfile(duration = 1800) {
  return EXPEDITION_LENGTHS[duration] || EXPEDITION_LENGTHS[1800];
}

export const MODE_DEFINITIONS: Record<string, ModeDefinition> = {
  normal: {
    endlessStart: 1800,
    bossInterval: 120,
    bossEscortAfter: 2400,
    doubleBossAfter: 3000,
    post30: {},
    name: "Padrão",
    label: "Padrão · 30 minutos",
    summary: "Padrão · 30 min",
    hud: "PADRÃO",
    duration: 1800,
    endless: false,
    clockRate: 1,
    savesProgress: true,
    xpMultiplier: 1,
    hpMultiplier: 1,
    damageMultiplier: 1,
    speedMultiplier: 1,
    spawnMultiplier: 1,
    enemyCapMultiplier: 1,
    eliteFrequency: 1,
    eliteHpMultiplier: 1,
    eliteDamageMultiplier: 1,
    bossHpMultiplier: 1,
    bossDamageMultiplier: 1,
    bossAttackRate: 1,
    formationSizeMultiplier: 1,
    formationIntervalMultiplier: 1,
    gemDropMultiplier: 1,
    rewardMultiplier: 1,
    completionBase: 250,
  },
  nightmare: {
    endlessStart: 1800,
    bossInterval: 120,
    bossEscortAfter: 2400,
    doubleBossAfter: 3000,
    post30: {},
    name: "Pesadelo",
    label: "Pesadelo · 30 minutos",
    summary: "Pesadelo · 30 min",
    hud: "PESADELO",
    duration: 1800,
    endless: false,
    clockRate: 1,
    savesProgress: true,
    xpMultiplier: 1,
    hpMultiplier: 1.35,
    damageMultiplier: 1.3,
    speedMultiplier: 1.08,
    spawnMultiplier: 1.35,
    enemyCapMultiplier: 1.2,
    eliteFrequency: 1.25,
    eliteHpMultiplier: 1.55,
    eliteDamageMultiplier: 1.35,
    bossHpMultiplier: 1.5,
    bossDamageMultiplier: 1.2,
    bossAttackRate: 1.12,
    formationSizeMultiplier: 1.15,
    formationIntervalMultiplier: 0.86,
    gemDropMultiplier: 1,
    rewardMultiplier: 1.25,
    completionBase: 250,
  },
  endless: {
    name: "Infinito",
    label: "Infinito · sobreviva o máximo possível",
    summary: "Infinito · sem limite",
    hud: "INFINITO",
    duration: null,
    endless: true,
    endlessStart: 1800,
    clockRate: 1,
    savesProgress: true,
    xpMultiplier: 1,
    hpMultiplier: 1,
    damageMultiplier: 1,
    speedMultiplier: 1,
    spawnMultiplier: 1,
    enemyCapMultiplier: 1,
    eliteFrequency: 1,
    eliteHpMultiplier: 1,
    eliteDamageMultiplier: 1,
    bossHpMultiplier: 1,
    bossDamageMultiplier: 1,
    bossAttackRate: 1,
    formationSizeMultiplier: 1,
    formationIntervalMultiplier: 1,
    gemDropMultiplier: 1,
    rewardMultiplier: 1,
    completionBase: 0,
    bossInterval: 120,
    bossEscortAfter: 2400,
    doubleBossAfter: 3000,
    post30: {
      hpPerMinute: 1.11,
      damagePerMinute: 1.07,
      spawnPerMinute: 1.06,
      bossHpPerMinute: 1.11,
      bossDamagePerMinute: 1.07,
      bossAttackPerMinute: 1.008,
      elitePerMinute: 0.045,
      eliteMax: 2.6,
      capPerMinute: 0.018,
      capMax: 1.34,
      formationPerMinute: 0.025,
      formationMax: 1.75,
      formationIntervalPerMinute: 0.012,
      formationIntervalMin: 0.62,
    },
  },
  test: {
    endlessStart: 1800,
    bossInterval: 120,
    bossEscortAfter: 2400,
    doubleBossAfter: 3000,
    post30: {},
    name: "Teste",
    label: "Teste · relógio 5× · sem salvar recompensas",
    summary: "Teste · relógio 5×",
    hud: "TESTE",
    duration: 1800,
    endless: false,
    clockRate: 5,
    savesProgress: false,
    xpMultiplier: 5,
    hpMultiplier: 1,
    damageMultiplier: 1,
    speedMultiplier: 1,
    spawnMultiplier: 1,
    enemyCapMultiplier: 1,
    eliteFrequency: 1,
    eliteHpMultiplier: 1,
    eliteDamageMultiplier: 1,
    bossHpMultiplier: 1,
    bossDamageMultiplier: 1,
    bossAttackRate: 1,
    formationSizeMultiplier: 1,
    formationIntervalMultiplier: 1,
    gemDropMultiplier: 1,
    rewardMultiplier: 1,
    completionBase: 250,
  },
};

export function getModeDefinition(id: string) {
  return MODE_DEFINITIONS[id] || MODE_DEFINITIONS.normal;
}

export function getModeScaling(id: string, time = 0) {
  const mode = getModeDefinition(id);
  const scale = {
    hp: mode.hpMultiplier,
    damage: mode.damageMultiplier,
    speed: mode.speedMultiplier,
    spawn: mode.spawnMultiplier,
    cap: mode.enemyCapMultiplier,
    elite: mode.eliteFrequency,
    eliteHp: mode.eliteHpMultiplier,
    eliteDamage: mode.eliteDamageMultiplier,
    bossHp: mode.bossHpMultiplier,
    bossDamage: mode.bossDamageMultiplier,
    bossAttack: mode.bossAttackRate,
    formation: mode.formationSizeMultiplier,
    formationInterval: mode.formationIntervalMultiplier,
    gemDrop: mode.gemDropMultiplier,
    reward: mode.rewardMultiplier,
  };
  if (!mode.endless || time < mode.endlessStart) return scale;
  const minutes = Math.max(0, (time - mode.endlessStart) / 60);
  const p = mode.post30;
  scale.hp *= Math.min(1e6, p.hpPerMinute ** minutes);
  scale.damage *= Math.min(1e4, p.damagePerMinute ** minutes);
  scale.spawn *= Math.min(8, p.spawnPerMinute ** minutes);
  scale.bossHp *= Math.min(1e6, p.bossHpPerMinute ** minutes);
  scale.bossDamage *= Math.min(1e4, p.bossDamagePerMinute ** minutes);
  scale.bossAttack *= Math.min(2.2, p.bossAttackPerMinute ** minutes);
  scale.elite *= Math.min(p.eliteMax, 1 + minutes * p.elitePerMinute);
  scale.cap *= Math.min(p.capMax, 1 + minutes * p.capPerMinute);
  scale.formation *= Math.min(
    p.formationMax,
    1 + minutes * p.formationPerMinute,
  );
  scale.formationInterval *= Math.max(
    p.formationIntervalMin,
    1 - minutes * p.formationIntervalPerMinute,
  );
  return scale;
}

export const MAX_ACTIVE_ENEMIES = 1100;
export const MAX_PRIORITY_ENEMIES = 8;
export const MAX_WORLD_PICKUPS = 260;

export const META_DEFINITIONS: Record<string, MetaDefinition> = OBELISK_NODES;

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: "survive",
    name: "Ainda há luz",
    text: "Sobreviva 5 minutos.",
    character: "orin",
    modes: ["normal"],
    check: (g: AchievementContext) => g.run.time >= 300,
  },
  {
    id: "thousand",
    name: "Mil ecos",
    text: "Derrote 1.000 inimigos em uma partida.",
    character: "ivo",
    modes: ["normal"],
    check: (g: AchievementContext) => g.run.kills >= 1000,
  },
  {
    id: "evolve",
    name: "Outra forma de arder",
    text: "Evolua uma arma.",
    character: "sena",
    modes: ["normal"],
    check: (g: AchievementContext) => g.run.evolutions > 0,
  },
  {
    id: "level",
    name: "Uma página adiante",
    text: "Alcance o nível 30.",
    reward: 100,
    check: (g: AchievementContext) => g.player.level >= 30,
  },
  {
    id: "boss",
    name: "O sino se cala",
    text: "Derrote um chefe.",
    reward: 80,
    check: (g: AchievementContext) => g.run.bossKills > 0,
  },
  {
    id: "complete",
    name: "Limiar atravessado",
    text: "Sobreviva aos 30 minutos.",
    modes: ["normal"],
    reward: 200,
    check: (g: AchievementContext) => g.run.completed,
  },
  {
    id: "first_structure",
    name: "A pedra responde",
    text: "Utilize sua primeira estrutura do mundo.",
    reward: 35,
    check: (g: AchievementContext) => (g.run.structuresUsed || 0) > 0,
  },
  {
    id: "urn_hundred",
    name: "Poeira de cem memórias",
    text: "Quebre 100 urnas em uma expedição.",
    reward: 80,
    check: (g: AchievementContext) => (g.run.urnsBroken || 0) >= 100,
  },
  {
    id: "exchange_altar",
    name: "Preço de sangue",
    text: "Aceite uma troca no Altar da Troca.",
    reward: 60,
    check: (g: AchievementContext) => g.run.usedExchange === true,
  },
  {
    id: "third_phase",
    name: "Até o núcleo",
    text: "Derrote um chefe depois de alcançar sua terceira fase.",
    reward: 90,
    check: (g: AchievementContext) => (g.run.phase3BossKills || 0) > 0,
  },
  {
    id: "first_synergy",
    name: "Dois ecos, uma forma",
    text: "Descubra sua primeira sinergia.",
    reward: 75,
    check: (g: AchievementContext) => (g.run.synergies || []).length > 0,
  },
  {
    id: "gardens",
    name: "Respirar sob a água",
    text: "Conclua os Jardins Submersos.",
    reward: 150,
    check: (g: AchievementContext) =>
      g.run.completed && g.run.mapId === "gardens",
  },
  {
    id: "austere",
    name: "Mãos vazias",
    text: "Conclua uma expedição sem usar consumíveis.",
    reward: 120,
    check: (g: AchievementContext) =>
      g.run.completed && (g.run.itemsUsed || 0) === 0,
  },
];

/* v1.2 — conteúdo data-driven adicional. */
export const SAVE_SCHEMA = 3;
export const CHUNK_SIZE = 640;
export const ACTIVE_CHUNK_RADIUS = 1;
export const RUN_INVENTORY_SLOTS = 4;

export const RARITY: Record<
  string,
  { name: string; color: string; weight: number }
> = {
  common: { name: "COMUM", color: "#afbbb5", weight: 62 },
  uncommon: { name: "INCOMUM", color: "#86d9bd", weight: 27 },
  rare: { name: "RARO", color: "#c7b1f0", weight: 9 },
  arcane: { name: "ARCANO", color: "#f0cb82", weight: 2 },
};

export const ITEM_DEFINITIONS: Record<string, ItemDefinition> = {
  sap_flask: {
    name: "Frasco de Seiva",
    icon: "♥",
    rarity: "common",
    maxStack: 3,
    weight: 18,
    text: "Recupera 38% da vitalidade máxima.",
    use: "heal",
  },
  ash_bomb: {
    name: "Bomba de Cinzas",
    icon: "✹",
    rarity: "uncommon",
    maxStack: 3,
    weight: 13,
    text: "Explode ao redor do eco e causa dano massivo.",
    use: "bomb",
  },
  split_hourglass: {
    name: "Ampulheta Partida",
    icon: "⌛",
    rarity: "rare",
    maxStack: 2,
    weight: 8,
    text: "Desacelera todos os inimigos próximos por 6 s.",
    use: "slow",
  },
  amber_seal: {
    name: "Selo de Âmbar",
    icon: "✷",
    rarity: "uncommon",
    maxStack: 3,
    weight: 11,
    text: "Amplifica dano e frequência por 14 s.",
    use: "buff",
  },
  nacre_veil: {
    name: "Véu de Nácar",
    icon: "◌",
    rarity: "rare",
    maxStack: 2,
    weight: 7,
    text: "Concede invulnerabilidade por 4 s.",
    use: "veil",
  },
  echo_magnet: {
    name: "Ímã de Ecos",
    icon: "⌖",
    rarity: "common",
    maxStack: 3,
    weight: 15,
    text: "Atrai todos os cristais carregados no mundo ativo.",
    use: "magnet",
  },
  obelisk_shard: {
    name: "Fragmento do Obelisco",
    icon: "◇",
    rarity: "arcane",
    maxStack: 2,
    weight: 4,
    text: "Eleva sorte e chance de drops por 30 s.",
    use: "luck",
  },
  basalt_key: {
    name: "Chave Basáltica",
    icon: "⚿",
    rarity: "rare",
    maxStack: 3,
    weight: 6,
    text: "Abre cofres selados encontrados no mundo.",
    use: "key",
  },
};

export const STATUS_DEFINITIONS: Record<string, StatusDefinition> = {
  slow: { maxStacks: 1, color: "#a8dfff" },
  freeze: { maxStacks: 1, color: "#d7f3ff" },
  burn: { maxStacks: 5, color: "#ffac75", tick: 0.5 },
  shock: { maxStacks: 3, color: "#ffe69d", tick: 0.4 },
  mark: { maxStacks: 1, color: "#c6b7ff" },
  poison: { maxStacks: 5, color: "#9edcaa", tick: 0.6 },
};

export const WEAPON_PATHS: Record<string, Record<string, PathDefinition>> = {
  ember: {
    detonation: {
      name: "Detonação",
      text: "Explosões maiores; menor frequência.",
      mods: { area: 1.35, cooldown: 1.18, blast: 1.7 },
    },
    combustion: {
      name: "Combustão",
      text: "Brasas aplicam queimadura prolongada.",
      mods: { damage: 0.92, burn: 1 },
    },
    shrapnel: {
      name: "Estilhaço",
      text: "Mais projéteis e perfuração; menor dano individual.",
      mods: { damage: 0.76, amount: 2, pierce: 2 },
    },
  },
  orbit: {
    bastion: {
      name: "Bastião",
      text: "Órbita menor, densa e com forte repulsão.",
      mods: { area: 0.82, damage: 1.25, knock: 1.8 },
    },
    eclipse: {
      name: "Eclipse",
      text: "Anéis alternam raio e deixam inimigos marcados.",
      mods: { mark: 1, amount: 1 },
    },
    fracture: {
      name: "Fratura",
      text: "Estilhaços orbitais soltam lascas ao acertar.",
      mods: { damage: 0.9, fragment: 1 },
    },
  },
  spear: {
    impalement: {
      name: "Empalamento",
      text: "Perfuração extrema e dano crescente em linha.",
      mods: { pierce: 8, damage: 1.18 },
    },
    omen: {
      name: "Presságio",
      text: "Agulhas marcam alvos; marcas aumentam críticos.",
      mods: { mark: 1, crit: 1 },
    },
    fan: {
      name: "Leque Abissal",
      text: "Mais agulhas em cone amplo; menor dano unitário.",
      mods: { amount: 2, damage: 0.8, spread: 1.5 },
    },
  },
  frost: {
    rime: {
      name: "Geada",
      text: "Lentidão muito mais intensa e duradoura.",
      mods: { slow: 1.8, area: 1.12 },
    },
    crystal: {
      name: "Cristalização",
      text: "Pulsos podem congelar inimigos comuns.",
      mods: { freeze: 1 },
    },
    rupture: {
      name: "Ruptura",
      text: "Alvos congelados explodem ao morrer.",
      mods: { shatter: 1, damage: 0.92 },
    },
  },
  chain: {
    conductor: {
      name: "Condutor",
      text: "Mais saltos e maior alcance entre alvos.",
      mods: { jumps: 3, chainRange: 1.2, damage: 0.88 },
    },
    overload: {
      name: "Sobrecarga",
      text: "Menos saltos, descargas muito mais violentas.",
      mods: { jumps: -2, damage: 1.65 },
    },
    storm: {
      name: "Tormenta",
      text: "Alvos afetados por status sofrem descarga adicional.",
      mods: { statusBurst: 1 },
    },
  },
  well: {
    cinder: {
      name: "Leito de Brasas",
      text: "Campos aplicam queimadura e duram menos.",
      mods: { burn: 1, duration: 0.82, damage: 1.18 },
    },
    gravity: {
      name: "Peso Morto",
      text: "Campos atraem mais cedo e com maior força.",
      mods: { pull: 1, area: 1.15 },
    },
    bloom: {
      name: "Florescimento",
      text: "Mais campos menores surgem por ataque.",
      mods: { amount: 2, area: 0.78, damage: 0.8 },
    },
  },
  disc: {
    saw: {
      name: "Serrilha",
      text: "Discos aceleram, cortam com mais força e atravessam a horda.",
      mods: { damage: 1.12, speed: 1.2 },
    },
    mirror: {
      name: "Espelho",
      text: "Retorno causa dano elevado e marca alvos.",
      mods: { returnDamage: 1.6, mark: 1 },
    },
    hail: {
      name: "Granizo",
      text: "Impactos em alvos lentos geram estilhaços gelados.",
      mods: { frostShard: 1, damage: 0.92 },
    },
  },
  meteor: {
    zenith: {
      name: "Zênite",
      text: "Impactos maiores e mais lentos, com dano brutal.",
      mods: { area: 1.35, damage: 1.45, cooldown: 1.15 },
    },
    constellation: {
      name: "Constelação",
      text: "Mais impactos menores espalhados pela tela.",
      mods: { amount: 2, area: 0.72, damage: 0.72 },
    },
    comet: {
      name: "Cometa Frio",
      text: "Alvos congelados estilhaçam no impacto.",
      mods: { shatter: 1, freezeBurst: 1 },
    },
  },
};

export const SYNERGY_DEFINITIONS: Record<
  string,
  { name: string; weapons: string[]; text: string }
> = {
  frozen_current: {
    name: "Corrente Branca",
    weapons: ["frost", "chain"],
    text: "Correntes em alvos congelados ganham salto e descarga extra.",
  },
  burning_garden: {
    name: "Jardim Incandescente",
    weapons: ["ember", "well"],
    text: "Campos de cinzas alimentam queimaduras e ampliam explosões.",
  },
  nacre_rime: {
    name: "Granizo de Nácar",
    weapons: ["frost", "disc"],
    text: "Discos contra alvos lentos lançam lascas geladas.",
  },
  marked_void: {
    name: "Geometria Fatal",
    weapons: ["spear", "chain"],
    text: "Descargas em alvos marcados causam dano crítico adicional.",
  },
  shattered_sky: {
    name: "Céu Estilhaçado",
    weapons: ["meteor", "frost"],
    text: "Meteoros quebram gelo em uma segunda explosão.",
  },
  ember_orbit: {
    name: "Coroa de Fornalha",
    weapons: ["ember", "orbit"],
    text: "Órbitas podem incendiar; brasas explodem marcas orbitais.",
  },
};

export const MAP_DEFINITIONS: Record<string, MapDefinition> = {
  ruins: {
    name: "Ruínas do Obelisco",
    icon: "◇",
    unlocked: true,
    description:
      "Pedra, névoa e fragmentos de uma arquitetura que ainda observa.",
    floor: "#101e24",
    water: false,
    structureDensity: 0.58,
    terrainDensity: 0.48,
    palette: {
      floor: "#101e24",
      accent: "#71998b",
      hazard: "#a65b85",
      water: "#153b40",
    },
    structures: [
      "urn",
      "fountain",
      "exchange",
      "memory",
      "rift_altar",
      "silence",
      "chest",
      "obelisk",
      "column",
      "wall",
      "stone",
      "tree",
      "ruin",
      "rift",
    ],
    enemyPool: [
      "husk",
      "dart",
      "tank",
      "swarm",
      "ranged",
      "burrower",
      "sentinel",
      "charger",
      "splitter",
    ],
    bosses: BOSS_EVENTS.map((_, i) => i),
    hazards: ["rift", "mist"],
    waveModifiers: { rate: 1, hp: 1, elite: 1 },
  },
  gardens: {
    name: "Jardins Submersos",
    icon: "≋",
    unlocked: true,
    description:
      "Ruínas alagadas, vegetação arcana e caminhos de pedra sob água rasa.",
    floor: "#0d2528",
    water: true,
    structureDensity: 0.68,
    terrainDensity: 0.55,
    palette: {
      floor: "#0d2528",
      accent: "#72aca1",
      hazard: "#749b77",
      water: "#153b40",
    },
    structures: [
      "urn",
      "fountain",
      "exchange",
      "memory",
      "rift_altar",
      "silence",
      "chest",
      "obelisk",
      "column",
      "stone",
      "tree",
      "ruin",
      "platform",
      "thorn",
    ],
    enemyPool: [
      "husk",
      "dart",
      "swarm",
      "ranged",
      "herald",
      "weaver",
      "burrower",
      "splitter",
    ],
    bosses: [0, 2, 4, 5, 7, 9],
    hazards: ["water", "thorn", "mist"],
    waveModifiers: { rate: 1.06, hp: 0.96, elite: 1.08 },
  },
};

export const STRUCTURE_DEFINITIONS: Record<string, StructureDefinition> = {
  urn: {
    name: "Urna de Ecos",
    kind: "BREAKABLE",
    r: 15,
    hp: 34,
    weight: 22,
    destructible: true,
    color: "#7f7667",
  },
  fountain: {
    name: "Fonte de Seiva",
    kind: "INTERACTIVE",
    r: 25,
    weight: 1.3,
    interactive: true,
    color: "#79b99a",
    rare: true,
  },
  exchange: {
    name: "Altar da Troca",
    kind: "INTERACTIVE",
    r: 28,
    weight: 0.7,
    interactive: true,
    color: "#d39a82",
    rare: true,
  },
  memory: {
    name: "Altar da Memória",
    kind: "INTERACTIVE",
    r: 27,
    weight: 0.6,
    interactive: true,
    color: "#a9a0d3",
    rare: true,
  },
  rift_altar: {
    name: "Altar da Fenda",
    kind: "INTERACTIVE",
    r: 29,
    weight: 0.35,
    interactive: true,
    color: "#cf7fad",
    rare: true,
  },
  silence: {
    name: "Altar do Silêncio",
    kind: "INTERACTIVE",
    r: 28,
    weight: 0.35,
    interactive: true,
    color: "#8da2a2",
    rare: true,
  },
  chest: {
    name: "Cofre Basáltico",
    kind: "INTERACTIVE",
    r: 25,
    weight: 0.7,
    interactive: true,
    collidable: true,
    color: "#d2b477",
    rare: true,
  },
  obelisk: {
    name: "Obelisco Fraturado",
    kind: "INTERACTIVE",
    r: 31,
    weight: 0.25,
    interactive: true,
    collidable: true,
    color: "#8dc2a5",
    rare: true,
  },
  column: {
    name: "Coluna Partida",
    kind: "COLLIDABLE",
    r: 23,
    weight: 5,
    collidable: true,
    color: "#46585a",
  },
  wall: {
    name: "Muro Afundado",
    kind: "COLLIDABLE",
    r: 31,
    weight: 4,
    collidable: true,
    color: "#3d5050",
  },
  stone: {
    name: "Pedra Arcana",
    kind: "COLLIDABLE",
    r: 20,
    weight: 6,
    collidable: true,
    color: "#40575a",
  },
  tree: {
    name: "Árvore de Sal",
    kind: "DECORATIVE",
    r: 20,
    weight: 5,
    color: "#476758",
  },
  ruin: {
    name: "Ruína Baixa",
    kind: "COLLIDABLE",
    r: 28,
    weight: 3.2,
    collidable: true,
    color: "#435153",
  },
  platform: {
    name: "Plataforma de Pedra",
    kind: "DECORATIVE",
    r: 42,
    weight: 3.5,
    color: "#506365",
  },
  rift: {
    name: "Fenda Pulsante",
    kind: "HAZARD",
    r: 36,
    weight: 2,
    hazard: true,
    color: "#a65b85",
  },
  thorn: {
    name: "Espinhos de Maré",
    kind: "HAZARD",
    r: 31,
    weight: 2,
    hazard: true,
    color: "#749b77",
  },
};

export const BOSS_PHASES: Record<string, string[]> = {
  default: [
    "FASE I — A VIGÍLIA",
    "FASE II — A PEDRA ABERTA",
    "FASE III — O NÚCLEO DESPERTO",
  ],
  "A Catedral Errante": [
    "FASE I — O ÁTRIO",
    "FASE II — A NAVE PARTIDA",
    "FASE III — O NÚCLEO EXPOSTO",
  ],
  "O Sineiro de Pedra": [
    "FASE I — O BADALO",
    "FASE II — O ECO DUPLO",
    "FASE III — O ÚLTIMO TOQUE",
  ],
};
