export const PVP = {
  tickHz: 25,
  snapshotHz: 10,
  hp: 100,
  speed: 220,
  radius: 13,
  roundSeconds: 90,
  reconnectSeconds: 30,
  maxRewindTicks: 4,
  arena: { width: 1000, height: 600 },
  winRounds: 2,
} as const;
export const PVP_LOADOUTS = {
  nara: {
    name: "Nara",
    basic: "Brasa",
    skill: "Lança de fogo",
    pulse: "Ruptura",
    dash: "Passo de cinza",
    color: "#ed9c75",
    basicDamage: 12,
    basicRange: 330,
    basicCooldown: 0.6,
    boltDamage: 25,
    boltSpeed: 440,
    pulseDamage: 20,
    pulseRadius: 105,
  },
  orin: {
    name: "Orin",
    basic: "Eco orbital",
    skill: "Poço errante",
    pulse: "Pulso gravitacional",
    dash: "Deslocamento",
    color: "#98cbb2",
    basicDamage: 14,
    basicRange: 290,
    basicCooldown: 0.7,
    boltDamage: 23,
    boltSpeed: 380,
    pulseDamage: 24,
    pulseRadius: 115,
  },
  ivo: {
    name: "Ivo",
    basic: "Lâmina",
    skill: "Disco perfurante",
    pulse: "Corte circular",
    dash: "Investida",
    color: "#d4c592",
    basicDamage: 10,
    basicRange: 380,
    basicCooldown: 0.55,
    boltDamage: 27,
    boltSpeed: 540,
    pulseDamage: 18,
    pulseRadius: 95,
  },
  sena: {
    name: "Sena",
    basic: "Raio",
    skill: "Estrela cadente",
    pulse: "Anel celeste",
    dash: "Passo astral",
    color: "#bba9df",
    basicDamage: 13,
    basicRange: 320,
    basicCooldown: 0.65,
    boltDamage: 24,
    boltSpeed: 460,
    pulseDamage: 22,
    pulseRadius: 105,
  },
} as const;
export type PvpCharacter = keyof typeof PVP_LOADOUTS;
export type PvpAbility = "none" | "basic" | "skill" | "pulse" | "dash";
