// Generated by assets:tiles:metadata. Static Next imports; no image loads at module scope.
import image0 from "../assets/tiles/ground/cave/source.png";
import metadata0 from "../assets/tiles/ground/cave/source.json";
import image1 from "../assets/tiles/ground/corrupted/source.png";
import metadata1 from "../assets/tiles/ground/corrupted/source.json";
import image2 from "../assets/tiles/ground/dead/source.png";
import metadata2 from "../assets/tiles/ground/dead/source.json";
import image3 from "../assets/tiles/ground/forest/source-a.png";
import metadata3 from "../assets/tiles/ground/forest/source-a.json";
import image4 from "../assets/tiles/ground/forest/source-b.png";
import metadata4 from "../assets/tiles/ground/forest/source-b.json";
import image5 from "../assets/tiles/ground/lava/source.png";
import metadata5 from "../assets/tiles/ground/lava/source.json";
import image6 from "../assets/tiles/ground/rock/source.png";
import metadata6 from "../assets/tiles/ground/rock/source.json";
import image7 from "../assets/tiles/ground/ruins/source.png";
import metadata7 from "../assets/tiles/ground/ruins/source.json";
import image8 from "../assets/tiles/ground/sand/source.png";
import metadata8 from "../assets/tiles/ground/sand/source.json";
import image9 from "../assets/tiles/ground/swamp/source.png";
import metadata9 from "../assets/tiles/ground/swamp/source.json";
import image10 from "../assets/tiles/props/beast_damage/source-a.png";
import metadata10 from "../assets/tiles/props/beast_damage/source-a.json";
import image11 from "../assets/tiles/props/cave/source.png";
import metadata11 from "../assets/tiles/props/cave/source.json";
import image12 from "../assets/tiles/props/corruption/source.png";
import metadata12 from "../assets/tiles/props/corruption/source.json";
import image13 from "../assets/tiles/props/crystals/source.png";
import metadata13 from "../assets/tiles/props/crystals/source.json";
import image14 from "../assets/tiles/props/minerals/source.png";
import metadata14 from "../assets/tiles/props/minerals/source.json";
import image15 from "../assets/tiles/props/mines/source.png";
import metadata15 from "../assets/tiles/props/mines/source.json";
import image16 from "../assets/tiles/props/rocks/source.png";
import metadata16 from "../assets/tiles/props/rocks/source.json";
import image17 from "../assets/tiles/props/ruins/source.png";
import metadata17 from "../assets/tiles/props/ruins/source.json";
import image18 from "../assets/tiles/props/swamp/source.png";
import metadata18 from "../assets/tiles/props/swamp/source.json";
import image19 from "../assets/tiles/props/trees/dead/source.png";
import metadata19 from "../assets/tiles/props/trees/dead/source.json";
import image20 from "../assets/tiles/props/trees/living/source.png";
import metadata20 from "../assets/tiles/props/trees/living/source.json";
import image21 from "../assets/tiles/props/trees/petrified/source.png";
import metadata21 from "../assets/tiles/props/trees/petrified/source.json";
import image22 from "../assets/tiles/props/volcano/source.png";
import metadata22 from "../assets/tiles/props/volcano/source.json";
export const TILE_SOURCES = [
  { image: image0, metadata: metadata0 },
  { image: image1, metadata: metadata1 },
  { image: image2, metadata: metadata2 },
  { image: image3, metadata: metadata3 },
  { image: image4, metadata: metadata4 },
  { image: image5, metadata: metadata5 },
  { image: image6, metadata: metadata6 },
  { image: image7, metadata: metadata7 },
  { image: image8, metadata: metadata8 },
  { image: image9, metadata: metadata9 },
  { image: image10, metadata: metadata10 },
  { image: image11, metadata: metadata11 },
  { image: image12, metadata: metadata12 },
  { image: image13, metadata: metadata13 },
  { image: image14, metadata: metadata14 },
  { image: image15, metadata: metadata15 },
  { image: image16, metadata: metadata16 },
  { image: image17, metadata: metadata17 },
  { image: image18, metadata: metadata18 },
  { image: image19, metadata: metadata19 },
  { image: image20, metadata: metadata20 },
  { image: image21, metadata: metadata21 },
  { image: image22, metadata: metadata22 }
];
