import { Project, SyntaxKind } from "ts-morph";
const project = new Project({ tsConfigFilePath: "tsconfig.json" });
const fields = {
  Player: {
    character: "string",
    x: "number",
    y: "number",
    r: "number",
    speed: "number",
    health: "number",
    maxHealth: "number",
    armor: "number",
    level: "number",
    xp: "number",
    xpToNextLevel: "number",
    weapons: "Weapon[]",
    passives: "Record<string,number>",
    stats: "T.Stats",
    dx: "number",
    dy: "number",
    invulnerable: "number",
    buff: "number",
    luckBuff: "number",
    inWater: "boolean",
    hurtFlash: "number",
  },
  Weapon: {
    id: "string",
    level: "number",
    evolved: "boolean",
    path: "string|null",
    pathLevel: "number",
    timer: "number",
    damageDealt: "number",
    kills: "number",
    shots: "number",
    hits: "number",
  },
  World: {
    g: "GameSimulation",
    mapId: "string",
    map: "T.MapDefinition",
    seed: "string",
    changes: "Record<string,T.StructureChange>",
    chunks: "Map<string,T.Chunk>",
    nearby: "T.Structure[]",
    interactive: "T.Structure|null",
    hazardClock: "number",
  },
  WaveDirector: {
    index: "number",
    spawnClock: "number",
    eliteClock: "number",
    formationClock: "number",
    eventIndex: "number",
    nextEndlessBossAt: "number",
    endlessBossIndex: "number",
  },
};
for (const sf of project.getSourceFiles("src/game/**/*.ts")) {
  for (const cl of sf.getClasses()) {
    for (const [name, type] of Object.entries(fields[cl.getName()] || {}))
      cl.addProperty({ name, type, hasExclamationToken: true });
  }
}
const catalog = project.getSourceFileOrThrow("src/game/content/catalog.ts");
const tables = {
  WEAPON_DEFINITIONS: "Record<string,WeaponDefinition>",
  PASSIVE_DEFINITIONS: "Record<string,PassiveDefinition>",
  CHARACTER_DEFINITIONS: "Record<string,CharacterDefinition>",
  ENEMY_DEFINITIONS: "Record<string,EnemyDefinition>",
  WAVE_TABLE: "WaveDefinition[]",
  BOSS_EVENTS: "BossEvent[]",
  MODE_DEFINITIONS: "Record<string,ModeDefinition>",
  META_DEFINITIONS: "Record<string,MetaDefinition>",
  ACHIEVEMENTS: "AchievementDefinition[]",
  ITEM_DEFINITIONS: "Record<string,ItemDefinition>",
  STATUS_DEFINITIONS: "Record<string,StatusDefinition>",
  WEAPON_PATHS: "Record<string,Record<string,PathDefinition>>",
  MAP_DEFINITIONS: "Record<string,MapDefinition>",
  STRUCTURE_DEFINITIONS: "Record<string,StructureDefinition>",
  BOSS_PHASES: "Record<string,string[]>",
  RARITY: "Record<string,{name:string;color:string;weight:number}>",
  SYNERGY_DEFINITIONS:
    "Record<string,{name:string;weapons:string[];text:string}>",
};
for (const [name, type] of Object.entries(tables))
  catalog.getVariableDeclarationOrThrow(name).setType(type);
// Contextual typing for extracted routines. Remaining diagnostics are handled explicitly.
const methods = {
  "GameSimulation.setState": ["string"],
  "GameSimulation.start": ["string", "string", "string", "string|null"],
  "GameSimulation.modeScaling": ["number"],
  "GameSimulation.currentEnemyCap": ["T.WaveDefinition"],
  "GameSimulation.pushPickup": ["T.Pickup"],
  "GameSimulation.saveSnapshot": ["boolean"],
  "GameSimulation.announce": ["string", "string"],
  "GameSimulation.updateMapEvents": ["number"],
  "GameSimulation.hasSynergy": ["string"],
  "GameSimulation.dropItemWeighted": ["number", "number", "string|null"],
  "GameSimulation.addItem": ["string", "number"],
  "GameSimulation.replaceInventorySlot": ["number"],
  "GameSimulation.consumeItem": ["string", "number"],
  "GameSimulation.useItem": ["number"],
  "GameSimulation.resolveStructure": ["T.Structure", "boolean"],
  "GameSimulation.update": ["number"],
  "GameSimulation.findValidSpawnPosition": ["number|null"],
  "GameSimulation.spawn": ["string", "number|null", "T.BossEvent|null"],
  "GameSimulation.spawnAt": [
    "string",
    "number",
    "number",
    "T.BossEvent|null",
    "Partial<T.Enemy>|null",
  ],
  "GameSimulation.updateStatusEffects": ["T.Enemy", "number"],
  "GameSimulation.updateBossPhase": ["T.Enemy"],
  "GameSimulation.updateEnemies": ["number"],
  "GameSimulation.hostile": ["T.Enemy", "number", "number", "number"],
  "GameSimulation.projectile": [
    "Weapon|null",
    "number",
    "number",
    "number",
    "number",
    "Partial<T.Bullet>",
  ],
  "GameSimulation.updateBullets": ["number"],
  "GameSimulation.damageEnemy": [
    "T.Enemy",
    "number",
    "Weapon|null",
    "number",
    "boolean",
    "{status?:string;area?:boolean;synergy?:boolean}",
  ],
  "GameSimulation.hurtPlayer": ["number"],
  "GameSimulation.blast": [
    "number",
    "number",
    "number",
    "number",
    "Weapon|null",
    "number",
    "number",
    "{noStructure?:boolean}",
  ],
  "GameSimulation.ring": ["number", "number", "number", "string"],
  "GameSimulation.area": [
    "number",
    "number",
    "number",
    "number",
    "Weapon|null",
    "number",
    "number",
    "string",
  ],
  "GameSimulation.enemyHazard": [
    "number",
    "number",
    "number",
    "number",
    "number",
    "number",
    "string",
  ],
  "GameSimulation.updateAreas": ["number"],
  "GameSimulation.drop": ["string", "number", "number", "number"],
  "GameSimulation.dropXP": ["number", "number", "number"],
  "GameSimulation.updateDrops": ["number"],
  "GameSimulation.choiceKey": ["T.Upgrade"],
  "GameSimulation.candidates": ["boolean"],
  "GameSimulation.pathChoices": ["Weapon"],
  "GameSimulation.applyUpgrade": ["T.Upgrade"],
  "GameSimulation.pickUpgrade": ["number"],
  "GameSimulation.banishChoice": ["number"],
  "GameSimulation.openChest": ["T.Pickup"],
  "GameSimulation.finish": ["boolean", "boolean"],
  "GameSimulation.spark": ["number", "number", "string", "number"],
  "GameSimulation.float": [
    "number",
    "number",
    "string|number",
    "string",
    "number",
  ],
  "GameSimulation.updateEffects": ["number"],
  "GameSimulation.debugSpawnStructure": ["string"],
  "GameSimulation.teleportChunk": ["number", "number"],
  "GameSimulation.debugKey": ["string"],
  "World.constructor": [
    "GameSimulation",
    "string",
    "string",
    "Record<string,T.StructureChange>",
  ],
  "World.chunkKey": ["number", "number"],
  "World.chunkCoords": ["number", "number"],
  "World.createChunk": ["number", "number"],
  "World.ensureChunkAt": ["number", "number"],
  "World.mark": ["T.Structure", "T.StructureChange"],
  "World.query": ["number", "number", "number", "(s:T.Structure)=>void"],
  "World.findInteractive": ["number", "number", "number"],
  "World.resolvePlayerMove": ["number", "number", "number", "number", "number"],
  "World.avoidEnemy": ["T.Enemy", "number", "number"],
  "World.damageBreakablesAt": ["number", "number", "number", "number"],
  "World.breakStructure": ["T.Structure"],
  "World.isWater": ["number", "number"],
  "World.updateHazards": ["number"],
  "Weapon.constructor": ["string"],
  "Weapon.values": ["Player"],
  "Weapon.update": ["GameSimulation", "number"],
  "WaveDirector.wavePool": ["GameSimulation", "T.WaveDefinition"],
  "WaveDirector.spawnEndlessBosses": ["GameSimulation", "number"],
  "WaveDirector.update": ["GameSimulation", "number"],
};
for (const sf of project.getSourceFiles("src/game/**/*.ts")) {
  for (const cl of sf.getClasses()) {
    for (const fn of [...cl.getConstructors(), ...cl.getMethods()]) {
      const name =
        fn.getKind() === SyntaxKind.Constructor ? "constructor" : fn.getName();
      const types = methods[cl.getName() + "." + name];
      types?.forEach((type, i) => fn.getParameters()[i]?.setType(type));
    }
  }
}
await project.save();
